<div class="video_view">
    <video></video>
</div>
<div class="video_playlist">
    Video Playlist
</div>
<div class="video_info">
    Info
</div>
<div class="video_comments">
    Comments
</div>
<style>
    .video_view {
        width: 800px;
        height:450px;
    }
    .video_view video {
        width:100%;
        height:100%;
    }
    .video_playlist {
    }
    .video_info {
    }
    .video_comments {
    }
</style>

