<div class="left">
    <?php echo date('l dS F Y'); ?>
</div>

<div class="centre">
<?php
echo APP_NAME;
if($this->apptitle) :
    echo ': ' . $this->apptitle;
    if($this->appsection) : echo ' - ' . $this->appsection; endif;
endif;
?>
</div>

<div class="right">
    <?php if(User::hasIdentity()) : ?>
    Logged in as <strong><?php echo User::getIdentity()->getUsername(); ?></strong> | <a href="/userinfo">User Info</a> | <a href="/logout">Logout</a>
    <?php else: ?>
        <a href="/login">Login</a>
    <?php endif; ?>
</div>
