<div id="blogs">
<?php if(Betabud_Auth::getInstance()->hasIdeniity()) : ?>
    <a href="/app/blog/write">Create a blog post &raquo;</a>
<?php else : ?>
    <a href="/login?redirect=/app/blog/write">Login to create a blog post &raquo;</a>
<?php endif; ?>
<br /><br />
<?php if(count($this->blogs) > 0) :
    foreach($this->blogs as $blog) : ?>
        <p><strong><?php echo $blog->getTitle(); ?></strong>
        <br /><i>By <?php echo $blog->getUser()->getUsername(); ?> on <?php echo $blog->getPublishedDate(); ?></i>
        <?php if($blog->isMine()) : ?>
            <a href="/app/blog/write?id=<?php echo $blog->getId(); ?>">Edit</a> |
            <a href="/app/blog/delete?id=<?php echo $blog->getId(); ?>">Delete</a>
        <?php endif; ?>
        </p>
        <p><?php echo $blog->getText(); ?></p>
        <br />
<?php
    endforeach;
else:
?>
<p>
No blogs to display.
</p>
<?php endif; ?>
</div>
